services:
  frontend:
    container_name: przytulisko-frontend
    build:
      context: ./frontend
      dockerfile: ../dockerfiles/frontend.dockerfile
    volumes:
      - ./frontend/src:/app/src
    ports:
      - '4200:4200'
  backend:
    container_name: przytulisko-backend
    build:
      context: ./backend
      dockerfile: ../dockerfiles/backend.dockerfile
    volumes:
      - ./backend/dist:/app/dist
      - ./backend/app/migrations/data:/app/dist/server/migrations/data
    ports:
      - '3000:3000'
    env_file:
      - ./env/backend.env
    depends_on:
      - mysql
  mysql:
    image: mysql
    container_name: przytulisko-mysql
    volumes:
      - przytulisko-db:/var/lib/mysql
    restart: always
    env_file:
      - ./env/mysql.env
volumes:
  przytulisko-db: